### PR TITLE
Fix of User Projects

### PR DESCRIPTION
**Pull request by toboil-features**

### CODE REVIEW

**Comment by zdenop** [comment]
Did you really make check of the links? 
E.g. https://www.impact-project.eu/ shows "This page has been disabled."

**Comment by toboil-features** [comment]
I checked only some of them.

**Comment by kuraga** [comment]
#73

**Comment by zdenop** [comment]
#73 is marked (from March 2022)  as "This pull request is still a work in progress" + it has conflicts that must be resolved  - so we can ignore it .

**Pull request merged**
