### PR TITLE
compiling from git: mention libicu-dev early on

### PR DESCRIPTION
**Pull request by bertsky**
(otherwise training tools will be deactivated)

### CODE REVIEW

**Review by stweil — COMMENTED** [review]
Which Linux distribution requires those packages explicitly?

Normally they are installed as dependencies, so there is no need for this commit.
See also our GitHub actions: they work without it.

**Comment by stweil** [comment]
Please re-open if those changes are really required for a Debian based Linux distribution.

**Comment by bertsky** [comment]
On Debian – in my case libpango1.0-dev did **not** pull libfribidi-dev...

**Comment by stweil** [comment]
I just checked that for Debian stable, old stable and old old stable: in all cases libpango1.0-dev has a unconditional dependency for libfribidi-dev, so any installation with libpango1.0-dev but without libfribidi-dev would be broken.

**Comment by bertsky** [comment]
Very strange.

**Comment by amitdo** [comment]
Reference: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libpango1.0-dev

**Comment by amitdo** [comment]
@bertsky,

Do you use any 3rd party repo for Debian packages?

**Comment by bertsky** [comment]
> Do you use any 3rd party repo for Debian packages?

Oops! I did have Debian `testing` in the sources list. Hence my versions of build-essential etc are actually from Debian trixie. But there, still, libpango1.0-dev depends on libfribidi-dev ...

**Comment by amitdo** [comment]
https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

**Comment by bertsky** [comment]
> https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

Indeed – that was not a good decision at the time. But I _did_ create a pin rule to prevent testing from slipping in unwarranted:

```
Package: *
Pin: release a=stable
Pin-Priority: 700

Package: *
Pin: release a=testing
Pin-Priority: 650
``` 

So IIUC it would only prefer that source if I requested certain versions...

**Comment by amitdo** [comment]
Basically you combined oldoldstable with nextnexttobethenextstable :-)

**Comment by bertsky** [comment]
> Basically you combined oldoldstable with nextnexttobethenextstable :-)

I know, I know – call me crazy!

**Pull request closed without merging**
