### PR TITLE
Updated Introduction part

### PR DESCRIPTION
**Pull request by SimranAnand1**

### CODE REVIEW

**Comment by SimranAnand1** [comment]
It is useful in Optical Character recognition.

**Comment by zdenop** [comment]
But it is not true. Google does not use tesseract anymore.

**Comment by stweil** [comment]
I think the text was copied from this source: https://opensource.google/projects/tesseract.

**Comment by zdenop** [comment]
Last info I got from our Google friends (and it was long time ago) - Google is not using tesseract anymore (OCR in Google Vision is totally different product).

I suggest to use information we can prove (and we can not prove what is happening inside companies).

**Pull request closed without merging**
